### PR TITLE
fix: #1484 autoValidateMode breaks invalidate method

### LINKED ISSUE #1484: [FormBuilder]: AutovalidateMode Always and onUserInteraction break invalidate method
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package/Plugin version

10.0.1

### Platforms

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [ ] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.0, on macOS 15.4 24E248 darwin-arm64, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc2)
[!] Xcode - develop for iOS and macOS (Xcode 16.2)
    ! CocoaPods 1.15.2 out of date (1.16.2 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.98.2)
[✓] Connected device (5 available)
    ! Error: Browsing on the local area network for Fw iPhone 15. Ensure the device is unlocked and attached with a
      cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for ChanathipiPad. Ensure the device is unlocked and attached with a
      cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for chanathip’s iPhone. Ensure the device is unlocked and attached
      with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Jarawee’s iPhone. Ensure the device is unlocked and attached with
      a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for PAK. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Intre . Ensure the device is unlocked and attached with a cable
      or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for BZ. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:form_builder_validators/form_builder_validators.dart';

void main() {
  runApp(const MaterialApp(home: SignupForm()));
}

class SignupForm extends StatefulWidget {
  const SignupForm({super.key});

  @override
  State<SignupForm> createState() => _SignupFormState();
}

class _SignupFormState extends State<SignupForm> {
  final _formKey = GlobalKey<FormBuilderState>();
  final _emailFieldKey = GlobalKey<FormBuilderFieldState>();
  AutovalidateMode autovalidateMode = AutovalidateMode.disabled;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Signup Form')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: FormBuilder(
          key: _formKey,
          autovalidateMode: autovalidateMode,
          child: Column(
            children: [
              FormBuilderTextField(
                name: 'full_name',
                decoration: const InputDecoration(labelText: 'Full Name'),
                validator: FormBuilderValidators.compose([
                  FormBuilderValidators.required(),
                ]),
              ),
              const SizedBox(height: 10),
              FormBuilderTextField(
                key: _emailFieldKey,
                name: 'email',
                decoration: const InputDecoration(labelText: 'Email'),
                validator: FormBuilderValidators.compose([
                  FormBuilderValidators.required(),
                  FormBuilderValidators.email(),
                ]),
              ),
              const SizedBox(height: 10),
              FormBuilderTextField(
                name: 'password',
                decoration: const InputDecoration(labelText: 'Password'),
                obscureText: true,
                validator: FormBuilderValidators.compose([
                  FormBuilderValidators.required(),
                  FormBuilderValidators.minLength(6),
                ]),
              ),
              const SizedBox(height: 10),
              FormBuilderTextField(
                name: 'confirm_password',
                autovalidateMode: AutovalidateMode.onUserInteraction,
                decoration: InputDecoration(
                  labelText: 'Confirm Password',
                  suffixIcon: (_formKey.currentState?.fields['confirm_password']?.hasError ?? false)
                      ? const Icon(Icons.error, color: Colors.red)
                      : const Icon(Icons.check, color: Colors.green),
                ),
                obscureText: true,
                validator: (value) => _formKey.currentState?.fields['password']?.value != value ? 'No coinciden' : null,
              ),
              const SizedBox(height: 10),
              FormBuilderFieldDecoration<bool>(
                name: 'test',
                validator: FormBuilderValidators.compose([
                  FormBuilderValidators.required(),
                  FormBuilderValidators.equal(true),
                ]),
                // initialValue: true,
                decoration: const InputDecoration(labelText: 'Accept Terms?'),
                builder: (FormFieldState<bool?> field) {
                  return InputDecorator(
                    decoration: InputDecoration(
                      errorText: field.errorText,
                    ),
                    child: SwitchListTile(
                      title: const Text('I have read and accept the terms of service.'),
                      onChanged: field.didChange,
                      value: field.value ?? false,
                    ),
                  );
                },
              ),
              const SizedBox(height: 10),
              ElevatedButton(
                onPressed: () {
                  if (_formKey.currentState?.saveAndValidate() ?? false) {
                    if (true) {
                      // Either invalidate using Form Key
                      _formKey.currentState?.fields['email']?.invalidate('Email already taken.');
                      // OR invalidate using Field Key
                      // _emailFieldKey.currentState?.invalidate('Email already taken.');
                    }
                  } else {
                    setState(() {
                      autovalidateMode = AutovalidateMode.onUserInteraction;
                    });
                    debugPrint(_formKey.currentState?.value.toString());
                  }
                },
                child: const Text('Signup'),
              )
            ],
          ),
        ),
      ),
    );
  }
}


```

</details>

### Current Behavior

` _formKey.currentState?.fields['email']?.invalidate('Email already taken.')`
 is not working when autovalidateMode = `always` or `onUserInteraction`

### Expected Behavior

invalidate should show errorr correctly when autovalidateMode = `always` or `onUserInteraction`

### Steps To Reproduce

from the example code that i provide
- tap Signup button once to set autovalidateMode = onUserInteraction.
- and then fill the form
- tap signup button again.

### Aditional information

i think the root cause is `forceErrorText` in the` super class `of `FormBuilderField` is null

Image
 
related issue https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/1281

### LINKED ISSUE #1485: FormBuilderFiled: Support forceErrorText
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package/Plugin version

10.0.1

### What you'd like to happen

On stable Flutter version, the FormField widget add the property `forceErrorText` https://github.com/flutter/flutter/pull/132903

### Alternatives you've considered

The FormBuilderFiled need to support this new property and adapt all descendent widgets for this

### Aditional information

_No response_

### PR DESCRIPTION
**Pull request by majumdersubhanu**
## Connection with issue(s)

Close #1484
Close #1485

## Solution description

Fixes an issue where `invalidate()` calls were being cleared by framework validation when `autovalidateMode` was active. It also introduces support for the new Flutter `forceErrorText` property across the core library.

### Key Changes:
1.  **`FormBuilderFieldState` Persistence Logic**:
    *   Changed the default value of `clearCustomError` in `validate()` from `true` to `false`. This prevents framework-triggered validation calls (which pass no arguments) from clearing manual errors.
    *   Updated `didChange()` to explicitly clear `_customErrorText`. This ensures that manual errors are removed as soon as the user interacts with the field, maintaining a logical UX.
2.  **`forceErrorText` Integration**:
    *   Added `forceErrorText` to `FormBuilderField`, `FormBuilderFieldDecoration`, and core field constructors.
    *   This aligns the library with Flutter's updated `FormField` API (introduced in v3.24), allowing for declarative external error management.
3.  **Enhanced Documentation**:
    *   Updated docstrings for `validate()` and `invalidate()` to reflect the updated behavior regarding custom error clearing.

<details>
<summary>Code used for the demo</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:form_builder_validators/form_builder_validators.dart';

void main() {
  runApp(const MaterialApp(home: SignupForm()));
}

class SignupForm extends StatefulWidget {
  const SignupForm({super.key});

  @override
  State<SignupForm> createState() => _SignupFormState();
}

class _SignupFormState extends State<SignupForm> {
  final _formKey = GlobalKey<FormBuilderState>();
  final _emailFieldKey = GlobalKey<FormBuilderFieldState>();
  AutovalidateMode autovalidateMode = AutovalidateMode.disabled;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Signup Form')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: FormBuilder(
          key: _formKey,
          autovalidateMode: autovalidateMode,
          child: Column(
            children: [
              FormBuilderTextField(
                name: 'full_name',
                decoration: const InputDecoration(labelText: 'Full Name'),
                validator: FormBuilderValidators.compose([
                  FormBuilderValidators.required(),
                ]),
              ),
              const SizedBox(height: 10),
              FormBuilderTextField(
                key: _emailFieldKey,
                name: 'email',
                decoration: const InputDecoration(labelText: 'Email'),
                validator: FormBuilderValidators.compose([
                  FormBuilderValidators.required(),
                  FormBuilderValidators.email(),
                ]),
              ),
              const SizedBox(height: 10),
              FormBuilderTextField(
                name: 'password',
                decoration: const InputDecoration(labelText: 'Password'),
                obscureText: true,
                validator: FormBuilderValidators.compose([
                  FormBuilderValidators.required(),
                  FormBuilderValidators.minLength(6),
                ]),
              ),
              const SizedBox(height: 10),
              FormBuilderTextField(
                name: 'confirm_password',
                autovalidateMode: AutovalidateMode.onUserInteraction,
                decoration: InputDecoration(
                  labelText: 'Confirm Password',
                  suffixIcon: (_formKey.currentState?.fields['confirm_password']?.hasError ?? false)
                      ? const Icon(Icons.error, color: Colors.red)
                      : const Icon(Icons.check, color: Colors.green),
                ),
                obscureText: true,
                validator: (value) => _formKey.currentState?.fields['password']?.value != value ? 'No coinciden' : null,
              ),
              const SizedBox(height: 10),
              FormBuilderFieldDecoration<bool>(
                name: 'test',
                validator: FormBuilderValidators.compose([
                  FormBuilderValidators.required(),
                  FormBuilderValidators.equal(true),
                ]),
                // initialValue: true,
                decoration: const InputDecoration(labelText: 'Accept Terms?'),
                builder: (FormFieldState<bool?> field) {
                  return InputDecorator(
                    decoration: InputDecoration(
                      errorText: field.errorText,
                    ),
                    child: SwitchListTile(
                      title: const Text('I have read and accept the terms of service.'),
                      onChanged: field.didChange,
                      value: field.value ?? false,
                    ),
                  );
                },
              ),
              const SizedBox(height: 10),
              ElevatedButton(
                onPressed: () {
                  if (_formKey.currentState?.saveAndValidate() ?? false) {
                    if (true) {
                      // Either invalidate using Form Key
                      _formKey.currentState?.fields['email']?.invalidate('Email already taken.');
                      // OR invalidate using Field Key
                      // _emailFieldKey.currentState?.invalidate('Email already taken.');
                    }
                  } else {
                    setState(() {
                      autovalidateMode = AutovalidateMode.onUserInteraction;
                    });
                    debugPrint(_formKey.currentState?.value.toString());
                  }
                },
                child: const Text('Signup'),
              )
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

## Screenshots or Videos

https://github.com/user-attachments/assets/905deac2-d025-4507-9173-40dd24e89460

## To Do

- [x] Read contributing guide
- [x] Check the original issue to confirm it is fully satisfied
- [x] Add solution description to help guide reviewers
- [x] Add unit test to verify new or fixed behaviour
- [x] If apply, add documentation to code properties and package readme

### CODE REVIEW

File: lib/src/form_builder_field.dart [hunk 1]
```diff
@@ -244,7 +248,7 @@ class FormBuilderFieldState<F extends FormBuilderField<T>, T>
   /// not because [autoScrollWhenFocusOnInvalid] is `true`.
   @override
   bool validate({
-    bool clearCustomError = true,
+    bool clearCustomError = false,
```
Comment (deandreamatias) [inline lib/src/form_builder_field.dart:256]: This is a breaking change. Need to add some advice for developers that use this method.
Maybe implement some dart fix (https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/blob/main/lib/fix_data.yaml)

**Review by deandreamatias — COMMENTED** [review]
On issue related, had this steps to reproduce, but I can't see this flow in your video

>     tap Signup button once to set autovalidateMode = onUserInteraction.
>     and then fill the form
>     tap signup button again.

Please can create a video following this steps? Thanks!

File: lib/src/form_builder_field.dart (hunk 1 above)
Comment (majumdersubhanu) [reply lib/src/form_builder_field.dart:256]: @deandreamatias I've updated the video to do the exact steps to reproduce, please have a look, I'll add the dart fix ASAP.

File: lib/src/form_builder_field.dart [hunk 2]
```diff
@@ -233,6 +233,11 @@ class FormBuilderFieldState<F extends FormBuilderField<T>, T>
 
   /// Validate field
   ///
+  /// **BREAKING CHANGE**:
+  /// In previous versions, calling `validate()` would automatically clear any custom errors set via `invalidate()`.
+  /// Now, `validate()` does not clear custom errors by default.
+  /// If you want to clear the custom error when validating, you must explicitly pass `clearCustomError: true`.
+  ///
```
Comment (majumdersubhanu) [inline lib/src/form_builder_field.dart:240]: @deandreamatias I've added the breaking change notice to Dartdoc. I don't think implementing a dart fix will work here since data-driven fixes in Dart are only triggered when static analysis finds an issue such as a compilation error or deprecated usage.

- validate must exist, as it is an overridden method from Flutter's FormFieldState.
- We cannot deprecate it (which would trigger the analyzer).
- The change merely involves passing an optional named parameter (`clearCustomError: false`), which is a valid syntax.

Since there's no compiler warning or error generated on existing, valid `validate()` calls, the static analysis tool won't flag anything and, ultimately, bypasses the file when a developer runs dart fix.

Comment (deandreamatias) [reply lib/src/form_builder_field.dart:240]: Try to advice developers in another way. Is a breaking change that need to be inform.
Maybe a major version? IDK. What do you think?

Comment (majumdersubhanu) [reply lib/src/form_builder_field.dart:240]: Yeah, I'd say according to SemVer convention this should be a major version since it's a silent behavioural change. Maybe depricate this for now, and change this in the next major version?
